version: '3'

services:
    api:
        tty: true
        stdin_open: true
        container_name: pte_api
        build: ./
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
        env_file:
            - .env

    db:
        image: postgres
        container_name: pte_db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        env_file:
            - .env
        volumes:
            - pte_postgres_data:/var/lib/postgresql/data/

volumes:
  pte_postgres_data: